In [134]:
import galois
import numpy as np
N = 7514777789 # guaranteed y<n
n = 500#1769611

In [146]:
pow(2, 499, N)

4595924770

1769611 lines

In [83]:
points = []
for line in open('encoded.txt', 'r').read().strip().split('\n'):
    p, q = line.split(' ')
    points.append((int(p), int(q)))
GF = galois.GF(N)

In [42]:
# 0 66
# 1 77611334
# 2 7296865972
# 3 6005985327
# 4 2768154539

# soln: y mod 7514777789
# mat:  x^i mod 7514777789 for i in 0...n

# 7296865972 mod 7514777789
# 3^i mod 7514777789

In [135]:
matrix = np.empty((n,n), dtype=np.uint64)
solution = np.empty(n, dtype=np.uint64)
row = np.empty(n, dtype=np.uint64)
j = 0
for point in points[0:n]:
    p, q = point
    solution[j] = q
    acc = 1
    for i in range(n): # len(points)
        matrix[j][i] = (acc % N)
        acc*=p
    # matrix.append(GF(row))
    j+=1

In [136]:
out = np.linalg.solve(GF(matrix), GF(solution))

In [137]:
out

GF([        66, 5363181419, 3525321203, 4661326722, 5293532548,
    6192080310, 7078541202, 1211576057, 3686491450, 7467998618,
     528963556, 5843311615, 1571010594, 1794133349, 3768222427,
    2611170724, 5440535998, 3329129339, 6081158564, 3993314291,
    2900906219, 2614262978, 4702555938,  710739434, 6306661443,
     640998202,  941221784, 4626315140, 4091013045, 3750793020,
    4807789144, 5086336147, 2831125259, 7271239238,   68288617,
    2366675799, 2822760863,  280291921, 4322770035,  904998394,
    4478419576,  972772154, 7077224026, 4333300035, 2981094603,
    4426748197, 7148946793, 3313508466,  202396100, 6377507595,
    3349132163, 3461384080, 1028292712, 6957981199,  569992150,
    7184904822, 5468401225, 2223027634, 4524766828, 5767297604,
    3999345208, 5029606450, 6777856559, 1050707537,  193957852,
    1112339801, 3559894814, 5034286685, 5288407766, 2529491997,
    7321542865, 2556781036, 3262197613, 5970673125, 6429944254,
    5913470817, 1119876817, 5227868741, 1024313271, 6945853493,
    2593965980, 1842589650, 6182010461, 6525884452, 5115433959,
    4799080292, 1232319543, 7181710337, 6833158710, 5332182817,
    5748471386, 3374831651, 7399691355, 7349248164, 3926315901,
     148507282, 2133851458, 2811729945, 1455379559,  865656646,
    2919347615, 4796744587, 3517512810, 2942756740, 7058851874,
    1982858912, 6420007656, 1710172440,  349123182, 6670628210,
    7069208446, 4086658891, 5205865006, 4171722853, 1890563333,
    3964627665, 6597110047, 7472112815,  558975066, 5672555338,
    2800451071, 1840639595, 7402146330,  235001855, 6680902646,
    2952977689, 3793089432, 2275491301, 3505982543, 5133637269,
    2890303376, 3813212634, 1207356083,  849956065, 1533348257,
    5726356175, 4454904440, 1483563029,  397732667, 2709517330,
     796849271, 6985861298, 6636350087, 1201331682, 2376962100,
    5618582441, 2865150595, 1945661731, 5991366713, 6023427277,
     175725269, 5627828933, 4576412023, 3440397072, 3436538553,
    2723243367, 7440375310, 1151209455,  585842289, 5477058054,
    1820561627, 1468268150, 1915933855,  975978093, 3434905663,
    5509791876,  853567394, 6799897764, 5853457669, 2971518354,
     309797518, 5648152620, 1577973335, 6874068088, 2626600817,
    5986361292, 2195009977, 1497458808, 4048861396, 2447238995,
    2344417897, 1919715366, 6181175880, 2697625523, 1162601080,
     205394620, 7078419582, 5981164885,  323736961, 4699369398,
    5329992304, 5265975367, 4455468526, 2830764567, 6822277300,
    3524699914, 1791913882, 7167705245, 1733963309, 6382789122,
    1174036248, 6357332958, 3310263430, 1072584593, 4539309548,
    4471474799, 1065421807, 3110542935, 2115019262, 1383892799,
    5078221731, 3348093228,  418240210, 3195620360, 7236854226,
     977527627, 6065386463, 5786611851, 4967489247,   70299364,
    5564412634, 4624072777, 6368041942, 6209762663, 4602361096,
    5121095894, 4400593132, 7152250755, 5112560893, 1433753795,
    5756097688, 2006163009,  752129850, 4355928330, 4756097096,
    5717883928, 2341031934,  939886675, 1899003948, 6900047748,
      53092507, 6584605927, 2267553329, 1570330262, 5735540335,
    4943458811, 3687204009, 2146408668, 3027351743, 5755116352,
    1694908132,  262584860, 5598384064, 2937509679, 4471811755,
    2230804433, 4830545899, 4494045599, 3540655122, 4054082760,
    7307213233, 6043858279, 1622980451,  530877021, 3331120001,
    5228004824, 1499829144, 5036794806, 5971485673, 5009839642,
    5908785104, 6935426912, 4578814587, 6109305889, 4401737877,
     369797486, 7455658160, 5522358330, 5751441165, 6091715471,
    1331949273, 6007105834, 7276649523,   94322518, 3290419463,
     240711166, 3771151515, 2771617781, 1594736398, 2755663180,
    7132175876, 3716372036, 5943504089, 4680444088, 5477679723,
    1197996331, 7098447692, 3270633093, 6663068928,  555419255,
    2683882875, 2666060478,  264524663, 1995843591, 4535491545,
    6996779514, 1564073787,  281263650, 4494688587, 6621782860,
    4821379554, 3024337224, 2276597555, 2164887240, 1974844316,
    6812714305, 5442720822, 2161213248, 5838845986,  764534498,
    3523642108, 4240732511, 6093354074, 5029601793,  982016392,
    1701730868, 6999423968, 4255599032, 3949281698, 3465924972,
    2175799533,  864409110, 6904261152, 3615999576, 6812011283,
    2072213643, 3209576487, 4558374877, 6104542876, 6454146849,
    3956032758, 4466965892, 7135268040, 6198051700, 1634009119,
    6763304675, 3936477600,  511131144, 7315131052,  468936734,
    2306167450, 4674551163, 4803316601, 3454360120, 5974752716,
    3007403544, 3582236985, 3048165422, 5249309928, 7322780433,
    3394834256, 7015297177, 7326185026,  745758585, 5954496115,
    7441386477, 6547378178, 3442152525, 3963794573, 2824138936,
     694894116, 4475696656, 2337810797,  573066674, 1385765960,
    2273645419, 4737758215, 7459072628, 2861039832,  348261227,
    6340204859,  429113981, 6043400860, 1721923509, 2334923064,
     289295528, 3372108025, 7236213787, 5266233429, 4607174534,
    7141774306, 5871136246, 4527032005,  559458615, 1460361725,
    4410413294, 1137895620, 4234664508, 5634158819, 5944394368,
    4255818970, 3931993591, 4309733570, 3182694744, 3008116799,
    6906221383, 3593536749, 2632111356, 6870376228,  339573776,
    3188152486, 5560574836, 2306426749, 3007482813, 2945652142,
    5422317040, 6314361887, 3546091658, 4368124071, 4584531294,
     477595635, 1058775291, 3764851533, 4098605764, 5176644685,
    2227729678,  829135153, 7033695223, 5428914109, 1955678697,
    6488276270, 1065040629,  974755255, 3278909928, 5888144310,
    6615312369,   15835380, 2136513040, 2479189787, 2300108835,
    7151335158, 6854783900,  535075676, 3541615419, 3463730655,
    5593742441, 5345124503, 2335581727, 1276610303, 1074833065,
    1434063034,  887650025, 2000783970, 6218531621, 3756325924,
     712946003, 3446635191, 3217478906, 6543412442, 4319880087,
    5441368703, 6816108891, 3087037071, 1198746794, 7451436039,
    4388533331,  842719418, 6688265543,  155095234, 5554143886,
    3410906638, 4686432664, 2570537323, 2190047457, 1239573959,
    2709624838, 1468544887, 5970211245,  178702533, 3672873795,
    3281674501, 7492455531, 2417514471, 5940549404, 4461270687,
     681198437,  528555356, 3466049610, 6330738880, 3185990737,
    6601889309, 6099954974, 3755247104, 1768732881, 1501805997,
    3489463195, 5182533412, 5307968586, 6549319186, 7411546820],
   order=7514777789)

In [143]:
import pandas as pd
df = pd.DataFrame(points, columns=["p", 'q'])

In [144]:
df.sort_values(by="q")

               p           q
0              0          66
547833    547833        3468
33225      33225        4008
107861    107861        9261
1130357  1130357       14793
...          ...         ...
1300654  1300654  7514765920
603188    603188  7514766097
314909    314909  7514766690
1298194  1298194  7514769973
146886    146886  7514772492

[1769611 rows x 2 columns]

In [ ]:
7514777789
7514772492

In [30]:
from sympy import factorint
factorint(7296865972)

{2: 2, 11: 1, 29: 1, 607: 1, 9421: 1}

In [24]:
bytearray(out.tolist()[:-1])

ValueError: byte must be in range(0, 256)